version: '3'
 
services:
  app:
    container_name: stubber-app
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9876:9876
    volumes:
      - ./tmp:/tmp # For debugging purposes
    tty: true
  frontend:
    container_name: stubber-ui
    build:
      context: ./stubber-ui
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
  db:
    image: postgres
    restart: always
    container_name: stubber-db
    user: ${DB_UID}:${DB_GID} # mapping user ns for permissions
    volumes: 
      - ${PG_DATA}:/var/lib/postgresql/data
      - ./data/database:/docker-entrypoint-initdb.d # init script for database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
volumes:
  dbdata:
